server:
  port: 8989

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 开启根据服务名动态获取路由地址
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
      - id: order_route    # 指定路由的唯一标识
        # lb代表转发后台服务使用负载均衡,order-server代表服务注册中心上的服务名
        uri: lb://order-server
        predicates:  # 指定路由的规则
        - Path=/order/**

      - id: account_route
        # lb代表负载均衡转发路由,account-server代表服务注册中心上的服务名
        uri: lb://account-server
        predicates:
        - Path=/account/**

      - id: storage_route
        # lb代表负载均衡转发路由,storage-server代表服务注册中心上的服务名
        uri: lb://storage-server
        predicates:
        - Path=/storage/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
